name: 'Update Umbrel App'
description: |
  Updates umbrel-app.yml files in Umbrel App Stores to mirror updates to associated docker compose files 
  and commits the result to the current branch.
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  source_service_name:
    description: 'Static service name to read the updated version from.'
    required: false
  fallback_service_name:
    description: 'Static service name to read the updated version from when cannot infer service from APP_HOST.'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
    - uses: mikefarah/yq@v4
      with:
        cmd: yq --version
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Update umbrel-app.yml
      run: update-version.sh "${{ inputs.source_service_name }}" "${{ inputs.fallback_service_name }}"
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update versions in umbrel-app.yml
    - name: Inform user of warnings
      if: env.WARNINGS_EMITTED == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `⚠️ Please review the [warnings](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) generated during processing.`
          })
